apiVersion: v1
kind: ConfigMap
metadata:
  name: document-analysis-service-config
  labels:
    app: document-analysis-service
    component: config
data:
  # Service configuration
  APP_SERVICE_NAME: "document-analysis-service"
  APP_SERVICE_VERSION: "1.0.0"
  APP_DEBUG: "false"

  # File size limits (in MB)
  APP_MAX_UPLOAD_SIZE_MB: "100"
  APP_MAX_S3_SIZE_MB: "1000"

  # CORS configuration
  APP_CORS_ORIGINS: '["*"]'

  # S3 endpoint (optional - configure if using S3)
  # APP_S3_ENDPOINT: "https://s3.amazonaws.com"
