apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: document-analysis

commonLabels:
  app.kubernetes.io/name: document-analysis-service
  app.kubernetes.io/part-of: document-analysis-platform

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- route.yaml

images:
- name: quay.io/wjackson/document-analysis
  newTag: latest
